### ISSUE TITLE
Parsing target volume fraction to Mote3D

### ISSUE THREAD

**Issue by bhaveshshrimali** [Mote3D/Mote3D_toolbox#2]
Hi, 
I was going through the main subroutine of Mote3D_toolbox. Are there any available extensions/modifications of the current code wherein the desired volume fraction could be parsed to the function (as opposed to the number of trials) as a stopping criteria? For instance, the current inputs just include the number of spheres and maximum number of trials required to place the spheres, as the stopping criteria ? 

Thanks

**Comment by Mote3D** [comment]
Hi,
 
yes, at the moment the stopping criteria are either the number of spheres or the number of positioning trials. Using the desired volume fraction is only straightforward for non-overlapping spheres with known diameter distribution. In this case you could select the number of spheres corresponding to the desired volume fraction during program initialisation.

As a workaround, you could use a simple while loop to automatically rerun Mote3D until the desired volume fraction has (approximately) been reached.
