### ISSUE TITLE
How to export the model in to ABAQUS?

### ISSUE THREAD

**Issue by alan1369** [Mote3D/Mote3D_toolbox#3]
Hi.

After generating the particles in some specific RVE, how we could access to "Dialog box for export format specification"? It doesn't appear to me. Should we install some particular library?
I'll be thankful if you guide me step by step. 

Thank you

**Comment by Mote3D** [comment]
Hello Alan,
please use the current Mote3d release that can be found [here](https://github.com/Mote3D/Mote3D_toolbox/releases/tag/v2.1). It contains all the files required to export the model geometry to Abaqus. Let me know if the problem persists.
